### ISSUE TITLE
Media folder is not created in the correct path

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Images#21]
The media folder is created next to the .exe file:

![image](https://cloud.githubusercontent.com/assets/566463/11895467/35baeaaa-a57f-11e5-8b18-10074d1aed9b.png)

For the app store apps, it should be as a child directory of `../content`

The same problem happens locally:

![image](https://cloud.githubusercontent.com/assets/566463/11895499/871f9f3a-a57f-11e5-9526-728c98cb5843.png)

For the local apps, it should be a child directory of `./wwwroot`

**Comment by warpech** [comment]
@per-samuelsson could this be related to recent changes with static folder bootstrapping? 

The Images app now does not show images neither when installed from the app store or started locally.

**Comment by andwah** [comment]
Changed the way uploaded fiels is saved, they are now saved under a folder named \UploadedFiles in the root of the starcounter installation. This was done so images survives an app upgrade.

**Comment by warpech** [comment]
> Changed the way uploaded fiels is saved, they are now saved under a folder named \UploadedFiles in the root of the starcounter installation. This was done so images survives an app upgrade.

From what I see, the files are now being saved at `C:\UploadedFiles`. 

Anyway, the original problem is fixed.
