### ISSUE TITLE
File upload dialog does not show up in Firefox

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Images#26]
Clicking on "Or select file" does not work in Firefox. Tested with Images 3.0.5

**Comment by warpech** [comment]
Drag and drop upload works ok in Firefox, though

**Comment by aloscha** [comment]
@warpech maybe we will add test for upload dialog?

**Comment by warpech** [comment]
I am fixing the problem. Adding the test is a good idea, though it is one of the hardest things to test

**Comment by warpech** [comment]
Fixed. I have created a separate issue for adding tests: #28

**Comment by warpech** [comment]
In result of this issue I have refactored `juicy-filedrop` a bit. Now it does not require `iron-ajax`

**Comment by aloscha** [comment]
@warpech there are some design bug on master after your changes (that issue).
Before your changes - "11 February 2016 15:12:10 - Fix puppet-redirect url - Konstantin" it looks:

![image](https://cloud.githubusercontent.com/assets/5141943/14853988/145ba18a-0c8e-11e6-9d6f-0cc4664e82a0.png)

After your changes - "20 April 2016 12:30:06 - upgrade juicy-filedrop (https://github.com/StarcounterSamples/Images/issues/26)" it looks:

![image](https://cloud.githubusercontent.com/assets/5141943/14853941/ed43b1dc-0c8d-11e6-9e31-7dba4f3f62df.png)

And when I try to add new one

![image](https://cloud.githubusercontent.com/assets/5141943/14853963/0047509a-0c8e-11e6-895a-c6f3d52112d3.png)

**Comment by aloscha** [comment]
I get new version of Juicy-filedrop and after update it inside sys folder, everything works. Please recheck and update juicy inside project.

**Comment by aloscha** [comment]
I take that bug.

**Comment by aloscha** [comment]
Ok I know why it's happens. @warpech when you upload `juicy-upload` you remove `paper-dialog` (propably because it's not occur in bowej.json). I add paper-dialog to that file and retrieve removes files.
