### ISSUE TITLE
Add Settings page

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Images#27]
Add Settings page (visible after clicking on Launcher's "cog" icon) with settings that make sense for current features of Images:

- Upload folder path
- Maximum file size

Related: https://github.com/StarcounterSamples/Images/issues/25

**Comment by aloscha** [comment]
Could you @warpech review current version:
- Simplified (branch Add-settings-page_#27: https://github.com/StarcounterSamples/Simplified/tree/Add-settings-page_%2327)
- Images (branch Add-settings-page_#27: https://github.com/StarcounterSamples/Images/tree/Add-settings-page_%2327)

**Comment by warpech** [comment]
I have only a few comments:

1. **Simplified:** The application is called `Images`, so the folder should be renamed to `Images` and the class to `ImagesSettings`.

2. **Images:** I have changed the upload folder path, but the application doesn't switch to use it. Could you please retest?

3. **Images.**: The word "Please" doesn't make sense in the settings form:
<img width="665" alt="screen shot 2016-05-10 at 11 28 02" src="https://cloud.githubusercontent.com/assets/566463/15141845/646a7fe8-16a2-11e6-8b4b-cb3893d37366.png">
Please change the labels to:

  - `Upload folder path`
  - `Maximum file size (bytes)`

**Comment by aloscha** [comment]
Fixed all comments.

Maybe instead of textbox use Browse Bootstrap - https://jsfiddle.net/jasny/vtGxm/?

**Comment by warpech** [comment]
The settings page has nothing to do with `input type="file"`, and the jsFiddle you provided is about replacing a file upload. Is this the correct issue?

Templates of sample apps should use the simplest HTML5 possible. And we do use Bootstrap to style the inputs. That's what the `class="form-control"` attribute is for.

**Comment by warpech** [comment]
Please fix typo in Images code: `RegiserSharedFolder` -> `RegisterSharedFolder `

@miyconst could you please provide a second pair of eyes for the review? If we are happy then this can be the reference for Settings pages in other apps.

**Comment by miyconst** [comment]
There are some points here and there I think should be improved, but current solution is good enough to merge.

The main points is that the mapped handlers should not be accessible from the outside world. Means `"/images/settings"` should be a partial and `SelfOnly`.

**Comment by warpech** [comment]
Great! @aloscha please add `SelfOnly` flag to it and merge to master.

**Comment by aloscha** [comment]
Add evewrything and merged to master. I close issue.
